"""
Django settings for portfolio_site project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path
import os

import dj_database_url
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def env(name, default='', cast=None):
    """Read env vars, then Render Secret Files at /etc/secrets/<name>."""
    value = config(name, default='')
    if value in (None, ''):
        for path in (Path('/etc/secrets') / name, BASE_DIR / name):
            if path.is_file():
                value = path.read_text(encoding='utf-8').strip()
                break
    if value in (None, ''):
        value = default
    if cast is bool:
        if isinstance(value, bool):
            return value
        return str(value).strip().lower() in {'1', 'true', 'yes', 'on'}
    if cast is int:
        return int(value) if str(value).strip() else default
    return value


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

SECRET_KEY = config('SECRET_KEY')

DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = [
    host.strip()
    for host in config(
        'ALLOWED_HOSTS',
        default='.onrender.com,localhost,127.0.0.1',
    ).split(',')
    if host.strip()
]

CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in config(
        'CSRF_TRUSTED_ORIGINS',
        default='https://mohit-portfolio-0vmy.onrender.com',
    ).split(',')
    if origin.strip()
]

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'home',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'portfolio_site.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'portfolio_site.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': config('DB_ENGINE', default='django.db.backends.postgresql'),
        'NAME': config('DB_NAME', default='mohit_portfolio'),
        'USER': config('DB_USER', default='postgres'),
        'PASSWORD': config('DB_PASSWORD', default=''),
        'HOST': config('DB_HOST', default='127.0.0.1'),
        'PORT': config('DB_PORT', default='5432'),
    }
}

if config('DATABASE_URL', default=''):
    DATABASES['default'] = dj_database_url.parse(
        config('DATABASE_URL'),
        conn_max_age=600,
    )


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': (
            'whitenoise.storage.CompressedStaticFilesStorage'
            if not DEBUG
            else 'django.contrib.staticfiles.storage.StaticFilesStorage'
        ),
    },
}

CONTACT_EMAIL = env(
    'CONTACT_EMAIL',
    default='mkymohitkumaryadav0@gmail.com',
)
WEB3FORMS_ACCESS_KEY = env('WEB3FORMS_ACCESS_KEY', default='').strip()
RESEND_API_KEY = env('RESEND_API_KEY', default='').strip()
SMTP_USER = env('EMAIL_HOST_USER', default='').strip()
SMTP_PASSWORD = env('EMAIL_HOST_PASSWORD', default='').replace(' ', '').strip()
DEFAULT_FROM_EMAIL = env(
    'DEFAULT_FROM_EMAIL',
    default=SMTP_USER or 'portfolio@localhost',
)

# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration
# Set EMAIL_HOST_USER + EMAIL_HOST_PASSWORD to send contact form mail via SMTP.
# Without them, Django only prints the message to server logs.

if SMTP_USER and SMTP_PASSWORD:
    email_host = env('EMAIL_HOST', default='smtp.gmail.com')
    email_port = env('EMAIL_PORT', default=465, cast=int)
    use_ssl = env('EMAIL_USE_SSL', default=False, cast=bool)
    use_tls = env('EMAIL_USE_TLS', default=True, cast=bool)
    # Render often drops Gmail on port 587 until gunicorn times out (HTTP 500).
    if os.environ.get('RENDER') and 'gmail.com' in email_host and email_port == 587:
        email_port = 465
        use_ssl = True
        use_tls = False
    elif email_port == 465:
        use_ssl = True
        use_tls = False
    MAILERS = {
        'default': {
            'BACKEND': 'django.core.mail.backends.smtp.EmailBackend',
            'OPTIONS': {
                'host': email_host,
                'port': email_port,
                'username': SMTP_USER,
                'password': SMTP_PASSWORD,
                'use_tls': use_tls,
                'use_ssl': use_ssl,
                'timeout': 8,
            },
        },
    }
else:
    MAILERS = {
        'default': {
            'BACKEND': 'django.core.mail.backends.console.EmailBackend',
        },
    }
