# Generated by Django 6.1 on 2026-09-10 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('degree', models.CharField(max_length=160)),
                ('institution', models.CharField(max_length=160)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('period', models.CharField(max_length=80)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Education',
                'ordering': ['order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.TextField()),
                ('expected_keywords', models.JSONField(blank=True, default=list)),
                ('expected_answer', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=80)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('total', models.PositiveIntegerField(default=0)),
                ('passed', models.PositiveIntegerField(default=0)),
                ('accuracy', models.FloatField(default=0)),
                ('groundedness', models.FloatField(default=0)),
                ('hallucination_rate', models.FloatField(default=0)),
                ('details', models.JSONField(blank=True, default=list)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=120)),
                ('company', models.CharField(max_length=120)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('period', models.CharField(max_length=80)),
                ('summary', models.CharField(blank=True, max_length=255)),
                ('bullets', models.JSONField(blank=True, default=list)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='GameNpc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('display_name', models.CharField(max_length=120)),
                ('persona', models.TextField()),
                ('greeting', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GitHubRepoCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('github_id', models.BigIntegerField(unique=True)),
                ('name', models.CharField(max_length=160)),
                ('full_name', models.CharField(max_length=220)),
                ('description', models.TextField(blank=True)),
                ('html_url', models.URLField()),
                ('language', models.CharField(blank=True, max_length=80)),
                ('stars', models.PositiveIntegerField(default=0)),
                ('forks', models.PositiveIntegerField(default=0)),
                ('topics', models.JSONField(blank=True, default=list)),
                ('pushed_at', models.DateTimeField(blank=True, null=True)),
                ('is_fork', models.BooleanField(default=False)),
                ('is_visible', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'GitHub repo',
                'verbose_name_plural': 'GitHub repos',
                'ordering': ['order', '-stars', '-pushed_at'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_type', models.CharField(choices=[('profile', 'Profile'), ('experience', 'Experience'), ('project', 'Project'), ('skill', 'Skill'), ('education', 'Education'), ('resume', 'Resume'), ('github', 'GitHub'), ('custom', 'Custom')], max_length=20)),
                ('source_id', models.CharField(blank=True, max_length=80)),
                ('title', models.CharField(max_length=160)),
                ('content', models.TextField()),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['source_type', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('kicker', models.CharField(blank=True, max_length=255)),
                ('tagline', models.CharField(blank=True, max_length=255)),
                ('overview', models.TextField(blank=True)),
                ('contribution', models.TextField(blank=True)),
                ('technical', models.TextField(blank=True)),
                ('bullets', models.JSONField(blank=True, default=list)),
                ('tech_stack', models.JSONField(blank=True, default=list)),
                ('live_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('badge', models.CharField(blank=True, max_length=80)),
                ('featured', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SiteProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(default='Mohit Kasture', max_length=120)),
                ('headline', models.CharField(blank=True, max_length=255)),
                ('subheadline', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('about', models.TextField(blank=True)),
                ('focus_items', models.JSONField(blank=True, default=list)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('linkedin_url', models.URLField(blank=True)),
                ('github_username', models.CharField(blank=True, default='Mohitkasture', max_length=80)),
                ('website_url', models.URLField(blank=True)),
                ('current_role', models.CharField(blank=True, max_length=255)),
                ('stack_line', models.CharField(blank=True, max_length=255)),
                ('focus_line', models.CharField(blank=True, max_length=255)),
                ('now_line', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Site profile',
                'verbose_name_plural': 'Site profile',
            },
        ),
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Skill categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('page_view', 'Page view'), ('project_view', 'Project view'), ('resume_download', 'Resume download'), ('github_click', 'GitHub click'), ('contact_submit', 'Contact submit'), ('ai_query', 'AI query'), ('resume_analyze', 'Resume analyze'), ('external_link', 'External link'), ('npc_chat', 'NPC chat')], max_length=40)),
                ('path', models.CharField(blank=True, max_length=255)),
                ('label', models.CharField(blank=True, max_length=160)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('session_key', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type', '-created_at'], name='home_analyt_event_t_59bdb7_idx')],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='home.skillcategory')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
